databases:
  - name: gateway-db-prod
    databaseName: gateway_db
    user: admin
    plan: free

services:
  # 1. FastAPI Backend (Web Service)
    databaseName: payment_gateway
    user: gateway_user
    plan: free

services:
  - type: web
    name: gateway-api-service
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: ohio # Ensure this matches your database region
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gateway-db-prod
          property: connectionString
      - key: PORT
        value: "8000"
      - key: TEST_MODE
        value: "true"
      - key: TEST_PAYMENT_SUCCESS
        value: "true"
      - key: TEST_PROCESSING_DELAY
        value: "1000"
      - key: MERCHANT_API_KEY
        value: key_test_abc123
      - key: MERCHANT_API_SECRET
        value: secret_test_xyz789


  # The Merchant Dashboard (Frontend)
  - type: web
    name: merchant-dashboard-ui
    runtime: static  # Mandatory for static sites in the new spec
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build  # Fixes the 'publishPath not found' error
    envVars:
      - key: REACT_APP_API_URL
        value: https://gateway-api-service.onrender.com

  # 3. Hosted Checkout (Static Site)
  - type: web
    name: checkout-page-ui
    runtime: static  # Mandatory for static sites in the new spec
    rootDir: checkout-page
    buildCommand: npm install && npm run build
    staticPublishPath: build  # Fixes the 'publishPath not found' error
    envVars:
      - key: REACT_APP_API_URL
        value: https://gateway-api-service.onrender.com
